import type { Metadata } from 'next';
import { LegalPage } from '../../components/legal/LegalPage';
import type { LegalPageContent } from '../../lib/legal';
import { SITE_NAME } from '../../lib/seo';

const PRIVACY_CONTENT = {
  slug: 'privacy',
  title: 'Privacy Policy',
  lastUpdated: 'March 10, 2026',
  intro: [
    `This Privacy Policy explains how ${SITE_NAME} ("Company," "we," "us") collects, uses, and shares information when you visit our website, contact us, or engage our services (collectively, the "Services"). By using the Services, you agree to this Policy.`
  ],
  sections: [
    {
      type: 'list',
      heading: 'Information We Collect',
      body: ['Please do not submit sensitive personal information such as government IDs, payment card data, or health data through the Services.'],
      items: [
        'Contact and business information such as name, company, role, email, phone, and location.',
        'Project and inquiry details you submit, including budgets, timelines, and requirements.',
        'Communication content and metadata when you email us or otherwise contact the Company.',
        'Technical data such as IP address, device type, browser, operating system, referral URLs, and access timestamps generated by standard server logs.'
      ]
    },
    {
      type: 'text',
      heading: 'Sources of Information',
      body: [
        'We collect information directly from you, automatically through your use of the Services, and from third parties such as service providers that support website hosting, communications, and security.'
      ]
    },
    {
      type: 'list',
      heading: 'How We Use Information',
      items: [
        'Respond to inquiries, evaluate project fit, and provide services.',
        'Operate, secure, and improve the Services.',
        'Communicate about proposals, contracts, and project delivery.',
        'Comply with legal obligations and enforce agreements.'
      ],
      body: ['We do not sell your personal information or use it for cross-context behavioral advertising.']
    },
    {
      type: 'text',
      heading: 'Legal Bases (EEA/UK)',
      body: [
        'If you are located in the EEA or UK, we rely on legitimate interests, contractual necessity, and your consent where required to process personal information.'
      ]
    },
    {
      type: 'text',
      heading: 'Sharing of Information',
      body: [
        'We may share information with trusted service providers that help us operate the Services, such as hosting, analytics, and communications vendors, under confidentiality obligations. We may also disclose information to comply with legal requirements or to protect the rights, safety, and security of the Company and our clients.'
      ]
    },
    {
      type: 'text',
      heading: 'Cookies and Analytics',
      body: [
        'We may use cookies or similar technologies for basic site functionality and to understand traffic patterns. If we enable additional analytics or marketing tools, we will update this Policy. You can control cookies through your browser settings.'
      ]
    },
    {
      type: 'text',
      heading: 'Data Retention',
      body: [
        'We retain information for as long as necessary to fulfill the purposes described in this Policy, comply with legal obligations, resolve disputes, and enforce our agreements.'
      ]
    },
    {
      type: 'text',
      heading: 'Security',
      body: [
        'We implement reasonable administrative, technical, and physical safeguards to protect personal information. No method of transmission or storage is completely secure, so we cannot guarantee absolute security.'
      ]
    },
    {
      type: 'text',
      heading: 'International Transfers',
      body: [
        'Your information may be processed in countries other than where you reside. When we transfer personal data internationally, we use appropriate safeguards as required by law.'
      ]
    },
    {
      type: 'text',
      heading: 'Your Rights',
      body: [
        'Depending on your location, you may have rights to access, correct, delete, or object to certain processing of your personal information. You may also have the right to lodge a complaint with a supervisory authority. To make a request, contact us at hello@livinginpixel.com.'
      ]
    },
    {
      type: 'text',
      heading: "Children's Privacy",
      body: ['The Services are not directed to children under 16, and we do not knowingly collect personal information from children.']
    },
    {
      type: 'text',
      heading: 'Changes to This Policy',
      body: [
        'We may update this Policy from time to time. We will revise the "Last updated" date at the top of this page when changes are made.'
      ]
    },
    {
      type: 'text',
      heading: 'Contact',
      body: ['For privacy-related inquiries, contact hello@livinginpixel.com.']
    }
  ]
} as const satisfies LegalPageContent;

export const metadata: Metadata = {
  title: PRIVACY_CONTENT.title
};

export default function PrivacyPage() {
  return <LegalPage content={PRIVACY_CONTENT} />;
}
